import type { Locale } from "@/lib/i18n";

/**
 * Pages légales : conditions générales de vente, politique de confidentialité, mentions légales.
 * Format compact [fr, ar, en, it]. Les clés `legal.*` sont éditables depuis /admin/site-content
 * (groupe « Pages légales ») : ces textes sont un modèle de départ à faire valider par le cabinet.
 * Variables disponibles dans les textes : {name} {address} {phone} {email}.
 */
type Row = readonly [fr: string, ar: string, en: string, it: string];

export type LegalPageKey = "terms" | "privacy" | "notice";

/** Nombre de sections de chaque page (clés legal.<page>.s1 … sN). */
export const LEGAL_SECTION_COUNT: Record<LegalPageKey, number> = { terms: 12, privacy: 10, notice: 6 };

export const LEGAL_PATHS: Record<LegalPageKey, string> = {
  terms: "/conditions-generales",
  privacy: "/confidentialite",
  notice: "/mentions-legales",
};

/** Date de dernière mise à jour affichée en tête de chaque page légale. */
export const LEGAL_UPDATED_AT = "2026-09-30";

const ROWS: Record<string, Row> = {
  // Éléments communs
  "legal.updated": ["Dernière mise à jour : {date}", "آخر تحديث: {date}", "Last updated: {date}", "Ultimo aggiornamento: {date}"],
  "legal.link.notice": ["Mentions légales", "الإشعارات القانونية", "Legal notice", "Note legali"],
  "legal.link.terms": ["Conditions de vente", "شروط البيع", "Terms of sale", "Condizioni di vendita"],
  "legal.link.privacy": ["Confidentialité", "الخصوصية", "Privacy", "Privacy"],
  "legal.consent.prefix": ["J'ai lu et j'accepte les", "قرأتُ وأوافق على", "I have read and accept the", "Ho letto e accetto le"],
  "legal.consent.terms": ["conditions générales de vente", "الشروط العامة للبيع", "terms of sale", "condizioni generali di vendita"],
  "legal.consent.and": ["et la", "و", "and the", "e la"],
  "legal.consent.privacy": ["politique de confidentialité", "سياسة الخصوصية", "privacy policy", "informativa sulla privacy"],

  // ---- Conditions générales de vente
  "legal.terms.title": ["Conditions générales de vente", "الشروط العامة للبيع", "Terms of sale", "Condizioni generali di vendita"],
  "legal.terms.intro": ["Les présentes conditions régissent les commandes de traduction passées sur ce site auprès de {name}. En passant commande, le client les accepte sans réserve.", "تنظّم هذه الشروط طلبات الترجمة المقدَّمة عبر هذا الموقع لدى {name}. وبتقديم الطلب يقبلها الحريف دون تحفّظ.", "These terms govern translation orders placed on this site with {name}. By placing an order, the client accepts them without reservation.", "Le presenti condizioni disciplinano gli ordini di traduzione effettuati su questo sito presso {name}. Effettuando un ordine, il cliente le accetta senza riserve."],
  "legal.terms.s1.title": ["1. Objet", "1. الموضوع", "1. Purpose", "1. Oggetto"],
  "legal.terms.s1.body": ["Le cabinet propose des services de traduction assermentée et d'interprétariat. Les présentes conditions définissent les droits et obligations de chaque partie pour toute commande passée en ligne.", "يقدّم المكتب خدمات الترجمة المحلّفة والترجمة الفورية. تحدّد هذه الشروط حقوق والتزامات كل طرف في كل طلب يُقدَّم عبر الإنترنت.", "The firm provides sworn translation and interpreting services. These terms set out each party's rights and obligations for any order placed online.", "Lo studio offre servizi di traduzione giurata e interpretariato. Le presenti condizioni definiscono diritti e obblighi di ciascuna parte per ogni ordine effettuato online."],
  "legal.terms.s2.title": ["2. Devis", "2. عرض السعر", "2. Quote", "2. Preventivo"],
  "legal.terms.s2.body": ["Le prix est calculé automatiquement à partir du tarif par page du service choisi, du nombre de pages et du délai demandé. Le cabinet peut réviser le devis si le document transmis diffère de celui décrit (nombre de pages, lisibilité).", "يُحتسب السعر تلقائيًا انطلاقًا من تعريفة الصفحة للخدمة المختارة وعدد الصفحات والأجل المطلوب. ويجوز للمكتب مراجعة عرض السعر إذا اختلفت الوثيقة المرسلة عن الموصوفة (عدد الصفحات، وضوح الخط).", "The price is calculated automatically from the per-page rate of the chosen service, the number of pages and the requested deadline. The firm may revise the quote if the document received differs from the one described (page count, legibility).", "Il prezzo è calcolato automaticamente in base alla tariffa per pagina del servizio scelto, al numero di pagine e alla scadenza richiesta. Lo studio può rivedere il preventivo se il documento ricevuto differisce da quello descritto (numero di pagine, leggibilità)."],
  "legal.terms.s3.title": ["3. Commande", "3. الطلب", "3. Order", "3. Ordine"],
  "legal.terms.s3.body": ["La commande est ferme lorsque le client accepte le devis dans son espace. Le travail ne démarre qu'après réception de l'acompte.", "يصبح الطلب نهائيًا عندما يقبل الحريف عرض السعر في فضائه. ولا يبدأ العمل إلا بعد استلام المقدّم.", "The order is binding once the client accepts the quote in their account. Work only starts after the deposit has been received.", "L'ordine è vincolante quando il cliente accetta il preventivo nella propria area. Il lavoro inizia solo dopo la ricezione dell'acconto."],
  "legal.terms.s4.title": ["4. Prix et paiement", "4. الأسعار والدفع", "4. Prices and payment", "4. Prezzi e pagamento"],
  "legal.terms.s4.body": ["Les prix sont exprimés en dinars tunisiens (TND). Le paiement s'effectue en deux temps : 50 % d'acompte à l'acceptation du devis, puis 50 % de solde avant la mise à disposition de la traduction finale. Les paiements sont traités par un prestataire sécurisé ; le cabinet ne conserve aucune donnée de carte bancaire.", "الأسعار بالدينار التونسي. يتم الدفع على مرحلتين: 50٪ مقدّمًا عند قبول عرض السعر، ثم 50٪ رصيدًا قبل إتاحة الترجمة النهائية. تُعالَج المدفوعات عبر مزوّد دفع آمن، ولا يحتفظ المكتب بأي بيانات بطاقة بنكية.", "Prices are in Tunisian dinars (TND). Payment is made in two steps: a 50% deposit when the quote is accepted, then the 50% balance before the final translation is made available. Payments are processed by a secure provider; the firm does not store any bank card data.", "I prezzi sono espressi in dinari tunisini (TND). Il pagamento avviene in due fasi: acconto del 50% all'accettazione del preventivo, poi saldo del 50% prima della messa a disposizione della traduzione finale. I pagamenti sono gestiti da un fornitore sicuro; lo studio non conserva alcun dato di carte bancarie."],
  "legal.terms.s5.title": ["5. Délais", "5. الآجال", "5. Deadlines", "5. Tempi di consegna"],
  "legal.terms.s5.body": ["Le délai choisi court à partir de la confirmation de l'acompte. Il est indicatif pour les documents complexes ou peu lisibles ; le cabinet informe le client de tout retard prévisible.", "يسري الأجل المختار ابتداءً من تأكيد المقدّم. وهو تقديري بالنسبة للوثائق المعقّدة أو غير الواضحة، ويُعلم المكتب الحريف بأي تأخير متوقَّع.", "The chosen deadline runs from confirmation of the deposit. It is indicative for complex or hard-to-read documents; the firm will inform the client of any foreseeable delay.", "La scadenza scelta decorre dalla conferma dell'acconto. È indicativa per documenti complessi o poco leggibili; lo studio informa il cliente di ogni ritardo prevedibile."],
  "legal.terms.s6.title": ["6. Livraison", "6. التسليم", "6. Delivery", "6. Consegna"],
  "legal.terms.s6.body": ["La traduction finale est mise à disposition dans l'espace client, au format numérique, dès la confirmation du paiement du solde. Les modalités d'une éventuelle remise d'un exemplaire papier sont convenues avec le client.", "تُتاح الترجمة النهائية في فضاء الحريف بصيغة رقمية فور تأكيد دفع الرصيد. وتُتَّفق مع الحريف على طرق تسليم نسخة ورقية عند الاقتضاء.", "The final translation is made available in the client area, in digital format, as soon as the balance payment is confirmed. Arrangements for any paper copy are agreed with the client.", "La traduzione finale è messa a disposizione nell'area cliente, in formato digitale, non appena il pagamento del saldo è confermato. Le modalità di un'eventuale copia cartacea sono concordate con il cliente."],
  "legal.terms.s7.title": ["7. Obligations du client", "7. التزامات الحريف", "7. Client obligations", "7. Obblighi del cliente"],
  "legal.terms.s7.body": ["Le client garantit que les documents transmis sont authentiques, lisibles et licites, et qu'il est en droit de les faire traduire. Le cabinet n'est pas responsable des conséquences d'un document falsifié ou incomplet.", "يضمن الحريف أن الوثائق المرسلة أصلية وواضحة ومشروعة، وأن له الحق في ترجمتها. ولا يتحمّل المكتب تبعات وثيقة مزوّرة أو ناقصة.", "The client guarantees that the documents supplied are authentic, legible and lawful, and that they are entitled to have them translated. The firm is not liable for the consequences of a forged or incomplete document.", "Il cliente garantisce che i documenti forniti sono autentici, leggibili e leciti e che ha diritto di farli tradurre. Lo studio non risponde delle conseguenze di un documento falsificato o incompleto."],
  "legal.terms.s8.title": ["8. Confidentialité", "8. السرية", "8. Confidentiality", "8. Riservatezza"],
  "legal.terms.s8.body": ["Le traducteur est tenu au secret professionnel. Les documents et informations transmis ne servent qu'à exécuter la commande et ne sont jamais divulgués à des tiers, sauf obligation légale.", "المترجم ملزم بالسر المهني. لا تُستعمل الوثائق والمعلومات المرسلة إلا لتنفيذ الطلب ولا تُفشى لأي طرف ثالث إلا بمقتضى القانون.", "The translator is bound by professional secrecy. Documents and information supplied are used only to carry out the order and are never disclosed to third parties, except where required by law.", "Il traduttore è vincolato al segreto professionale. I documenti e le informazioni forniti servono solo per eseguire l'ordine e non sono mai divulgati a terzi, salvo obbligo di legge."],
  "legal.terms.s9.title": ["9. Annulation et remboursement", "9. الإلغاء والاسترجاع", "9. Cancellation and refunds", "9. Annullamento e rimborso"],
  "legal.terms.s9.body": ["Tant que la traduction n'a pas commencé, le client peut annuler sa commande et l'acompte lui est remboursé. Une fois le travail commencé, l'acompte reste acquis au cabinet en contrepartie du travail déjà réalisé.", "ما دامت الترجمة لم تبدأ، يمكن للحريف إلغاء طلبه ويُسترجع له المقدّم. وبمجرد بدء العمل يبقى المقدّم من حق المكتب مقابل العمل المنجز.", "As long as the translation has not started, the client may cancel the order and the deposit is refunded. Once work has begun, the deposit is retained by the firm in return for the work already done.", "Finché la traduzione non è iniziata, il cliente può annullare l'ordine e l'acconto viene rimborsato. Una volta iniziato il lavoro, l'acconto resta allo studio a fronte del lavoro già svolto."],
  "legal.terms.s10.title": ["10. Réclamations", "10. الشكاوى", "10. Complaints", "10. Reclami"],
  "legal.terms.s10.body": ["Toute erreur de traduction imputable au cabinet est corrigée gratuitement si elle est signalée dans un délai raisonnable après la livraison. Les réclamations s'adressent à {email}.", "يُصحَّح مجانًا كل خطأ في الترجمة يُنسب إلى المكتب إذا أُبلغ عنه في أجل معقول بعد التسليم. تُوجَّه الشكاوى إلى {email}.", "Any translation error attributable to the firm is corrected free of charge if reported within a reasonable time after delivery. Complaints should be sent to {email}.", "Ogni errore di traduzione imputabile allo studio viene corretto gratuitamente se segnalato entro un termine ragionevole dalla consegna. I reclami vanno inviati a {email}."],
  "legal.terms.s11.title": ["11. Responsabilité", "11. المسؤولية", "11. Liability", "11. Responsabilità"],
  "legal.terms.s11.body": ["La responsabilité du cabinet est limitée au montant de la commande concernée. Elle ne peut être engagée pour l'usage que le client ou une autorité destinataire fait de la traduction, ni pour un refus administratif.", "تنحصر مسؤولية المكتب في مبلغ الطلب المعني. ولا تقوم عن الاستعمال الذي يجريه الحريف أو أي جهة مستلِمة للترجمة، ولا عن أي رفض إداري.", "The firm's liability is limited to the amount of the order concerned. It cannot be engaged for the use the client or a receiving authority makes of the translation, nor for an administrative refusal.", "La responsabilità dello studio è limitata all'importo dell'ordine in questione. Non può essere invocata per l'uso che il cliente o un'autorità destinataria fa della traduzione, né per un rifiuto amministrativo."],
  "legal.terms.s12.title": ["12. Droit applicable et litiges", "12. القانون الواجب التطبيق والنزاعات", "12. Governing law and disputes", "12. Legge applicabile e controversie"],
  "legal.terms.s12.body": ["Les présentes conditions sont soumises au droit tunisien. À défaut de règlement amiable, les tribunaux compétents de Tunis sont seuls compétents.", "تخضع هذه الشروط للقانون التونسي. وعند تعذّر التسوية الودية تختص محاكم تونس المختصة وحدها.", "These terms are governed by Tunisian law. Failing an amicable settlement, the competent courts of Tunis have sole jurisdiction.", "Le presenti condizioni sono soggette al diritto tunisino. In mancanza di composizione amichevole, sono competenti in via esclusiva i tribunali di Tunisi."],

  // ---- Politique de confidentialité
  "legal.privacy.title": ["Politique de confidentialité", "سياسة الخصوصية", "Privacy policy", "Informativa sulla privacy"],
  "legal.privacy.intro": ["Le cabinet protège vos données personnelles conformément à la loi organique tunisienne n° 2004-63 du 27 juillet 2004 relative à la protection des données à caractère personnel.", "يحمي المكتب بياناتكم الشخصية طبقًا للقانون الأساسي التونسي عدد 63 لسنة 2004 المؤرخ في 27 جويلية 2004 المتعلق بحماية المعطيات الشخصية.", "The firm protects your personal data in accordance with Tunisian Organic Law No. 2004-63 of 27 July 2004 on the protection of personal data.", "Lo studio protegge i tuoi dati personali in conformità alla legge organica tunisina n. 2004-63 del 27 luglio 2004 sulla protezione dei dati personali."],
  "legal.privacy.s1.title": ["1. Responsable du traitement", "1. المسؤول عن المعالجة", "1. Data controller", "1. Titolare del trattamento"],
  "legal.privacy.s1.body": ["Le responsable du traitement est {name}, {address}. Contact : {email}.", "المسؤول عن المعالجة هو {name}، {address}. للاتصال: {email}.", "The data controller is {name}, {address}. Contact: {email}.", "Il titolare del trattamento è {name}, {address}. Contatto: {email}."],
  "legal.privacy.s2.title": ["2. Données collectées", "2. المعطيات المجمَّعة", "2. Data collected", "2. Dati raccolti"],
  "legal.privacy.s2.body": ["Nous collectons votre identité et vos coordonnées (nom, email, téléphone), les documents que vous nous confiez, l'historique de vos commandes et paiements, ainsi que des données techniques de connexion nécessaires à la sécurité du site.", "نجمع هويتكم وبيانات الاتصال (الاسم، البريد الإلكتروني، الهاتف)، والوثائق التي تودعونها لدينا، وسجل طلباتكم ومدفوعاتكم، إضافة إلى بيانات الاتصال التقنية اللازمة لأمن الموقع.", "We collect your identity and contact details (name, email, phone), the documents you entrust to us, your order and payment history, and technical connection data needed for site security.", "Raccogliamo la tua identità e i tuoi recapiti (nome, email, telefono), i documenti che ci affidi, la cronologia di ordini e pagamenti e i dati tecnici di connessione necessari alla sicurezza del sito."],
  "legal.privacy.s3.title": ["3. Finalités", "3. الغايات", "3. Purposes", "3. Finalità"],
  "legal.privacy.s3.body": ["Ces données servent uniquement à exécuter vos commandes, gérer votre compte, assurer la sécurité du service, respecter nos obligations légales et vous contacter au sujet de vos dossiers.", "تُستعمل هذه المعطيات فقط لتنفيذ طلباتكم وإدارة حسابكم وضمان أمن الخدمة واحترام التزاماتنا القانونية والاتصال بكم بشأن ملفاتكم.", "This data is used only to carry out your orders, manage your account, keep the service secure, meet our legal obligations and contact you about your files.", "Questi dati servono solo per eseguire i tuoi ordini, gestire il tuo account, garantire la sicurezza del servizio, rispettare gli obblighi di legge e contattarti in merito alle tue pratiche."],
  "legal.privacy.s4.title": ["4. Confidentialité des documents", "4. سرية الوثائق", "4. Document confidentiality", "4. Riservatezza dei documenti"],
  "legal.privacy.s4.body": ["Vos documents sont stockés dans un espace privé, jamais accessible publiquement. Seuls vous et le traducteur y avez accès, et chaque téléchargement est enregistré.", "تُحفظ وثائقكم في فضاء خاص لا يمكن الوصول إليه علنًا. لا يطّلع عليها سواكم والمترجم، ويُسجَّل كل تنزيل.", "Your documents are stored in a private space that is never publicly accessible. Only you and the translator can access them, and every download is logged.", "I tuoi documenti sono archiviati in uno spazio privato mai accessibile pubblicamente. Solo tu e il traduttore potete accedervi e ogni download viene registrato."],
  "legal.privacy.s5.title": ["5. Durée de conservation", "5. مدة الاحتفاظ", "5. Retention", "5. Conservazione"],
  "legal.privacy.s5.body": ["Vos données sont conservées le temps nécessaire à l'exécution de la commande et au respect des obligations légales et comptables, puis supprimées ou anonymisées.", "تُحفظ معطياتكم للمدة اللازمة لتنفيذ الطلب واحترام الالتزامات القانونية والمحاسبية، ثم تُحذف أو تُجهَّل هويتها.", "Your data is kept for as long as needed to carry out the order and meet legal and accounting obligations, then deleted or anonymised.", "I tuoi dati sono conservati per il tempo necessario all'esecuzione dell'ordine e al rispetto degli obblighi legali e contabili, poi cancellati o anonimizzati."],
  "legal.privacy.s6.title": ["6. Destinataires", "6. المستلمون", "6. Recipients", "6. Destinatari"],
  "legal.privacy.s6.body": ["Vos données ne sont ni vendues ni cédées. Elles peuvent être traitées par nos prestataires techniques (hébergement, paiement en ligne, envoi d'emails), tenus à la confidentialité et agissant sur nos instructions.", "لا تُباع معطياتكم ولا تُحال. وقد يعالجها مزوّدونا التقنيون (الاستضافة، الدفع الإلكتروني، إرسال البريد) الملزمون بالسرية والعاملون بتعليماتنا.", "Your data is neither sold nor transferred. It may be processed by our technical providers (hosting, online payment, email delivery), who are bound by confidentiality and act on our instructions.", "I tuoi dati non sono venduti né ceduti. Possono essere trattati dai nostri fornitori tecnici (hosting, pagamento online, invio email), tenuti alla riservatezza e che agiscono secondo le nostre istruzioni."],
  "legal.privacy.s7.title": ["7. Vos droits", "7. حقوقكم", "7. Your rights", "7. I tuoi diritti"],
  "legal.privacy.s7.body": ["Vous disposez d'un droit d'accès, de rectification, d'opposition et de suppression de vos données. Pour l'exercer, écrivez à {email}. Vous pouvez aussi saisir l'Instance nationale de protection des données personnelles (INPDP).", "لكم حق النفاذ إلى معطياتكم وتصحيحها والاعتراض على معالجتها وحذفها. لممارسته راسلوا {email}. ويمكنكم أيضًا اللجوء إلى الهيئة الوطنية لحماية المعطيات الشخصية.", "You have the right to access, rectify, object to and delete your data. To exercise it, write to {email}. You may also contact the National Authority for the Protection of Personal Data (INPDP).", "Hai diritto di accesso, rettifica, opposizione e cancellazione dei tuoi dati. Per esercitarlo scrivi a {email}. Puoi anche rivolgerti all'Autorità nazionale per la protezione dei dati personali (INPDP)."],
  "legal.privacy.s8.title": ["8. Cookies", "8. ملفات تعريف الارتباط", "8. Cookies", "8. Cookie"],
  "legal.privacy.s8.body": ["Le site n'utilise que des cookies indispensables : votre session de connexion et votre langue préférée. Aucun cookie publicitaire ni de suivi n'est déposé.", "لا يستعمل الموقع سوى ملفات ارتباط ضرورية: جلسة الدخول ولغتكم المفضلة. ولا توضع أي ملفات إعلانية أو تتبّعية.", "The site only uses essential cookies: your login session and your preferred language. No advertising or tracking cookies are set.", "Il sito utilizza solo cookie indispensabili: la sessione di accesso e la lingua preferita. Non vengono installati cookie pubblicitari o di tracciamento."],
  "legal.privacy.s9.title": ["9. Sécurité", "9. الأمان", "9. Security", "9. Sicurezza"],
  "legal.privacy.s9.body": ["Nous appliquons des mesures techniques et organisationnelles adaptées : connexions chiffrées, mots de passe protégés, accès contrôlé aux documents et journalisation des opérations sensibles.", "نطبّق تدابير تقنية وتنظيمية ملائمة: اتصالات مشفّرة، وكلمات مرور محمية، ووصولًا مراقبًا إلى الوثائق، وتسجيلًا للعمليات الحساسة.", "We apply appropriate technical and organisational measures: encrypted connections, protected passwords, controlled access to documents and logging of sensitive operations.", "Applichiamo misure tecniche e organizzative adeguate: connessioni cifrate, password protette, accesso controllato ai documenti e registrazione delle operazioni sensibili."],
  "legal.privacy.s10.title": ["10. Modifications", "10. التعديلات", "10. Changes", "10. Modifiche"],
  "legal.privacy.s10.body": ["Cette politique peut évoluer. La date de dernière mise à jour figure en haut de la page.", "قد تتطور هذه السياسة. يظهر تاريخ آخر تحديث في أعلى الصفحة.", "This policy may change. The date of the last update is shown at the top of the page.", "La presente informativa può cambiare. La data dell'ultimo aggiornamento è indicata in cima alla pagina."],

  // ---- Mentions légales
  "legal.notice.title": ["Mentions légales", "الإشعارات القانونية", "Legal notice", "Note legali"],
  "legal.notice.intro": ["Informations légales relatives au site et à son éditeur.", "معلومات قانونية تخص الموقع وناشره.", "Legal information about the site and its publisher.", "Informazioni legali sul sito e sul suo editore."],
  "legal.notice.registration": ["", "", "", ""],
  "legal.notice.s1.title": ["1. Éditeur du site", "1. ناشر الموقع", "1. Site publisher", "1. Editore del sito"],
  "legal.notice.s1.body": ["Ce site est édité par {name}, traducteur et interprète assermenté. Adresse : {address}. Téléphone : {phone}. Email : {email}.", "يُنشر هذا الموقع من طرف {name}، مترجم وترجمان محلّف. العنوان: {address}. الهاتف: {phone}. البريد الإلكتروني: {email}.", "This site is published by {name}, sworn translator and interpreter. Address: {address}. Phone: {phone}. Email: {email}.", "Questo sito è pubblicato da {name}, traduttore e interprete giurato. Indirizzo: {address}. Telefono: {phone}. Email: {email}."],
  "legal.notice.s2.title": ["2. Statut professionnel", "2. الصفة المهنية", "2. Professional status", "2. Status professionale"],
  "legal.notice.s2.body": ["Traducteur et interprète assermenté près la Cour d'appel de Tunis. {registration}", "مترجم وترجمان محلّف لدى محكمة الاستئناف بتونس. {registration}", "Sworn translator and interpreter at the Tunis Court of Appeal. {registration}", "Traduttore e interprete giurato presso la Corte d'appello di Tunisi. {registration}"],
  "legal.notice.s3.title": ["3. Hébergement", "3. الاستضافة", "3. Hosting", "3. Hosting"],
  "legal.notice.s3.body": ["Les informations relatives à l'hébergeur du site sont communiquées sur simple demande à {email}.", "تُقدَّم المعلومات المتعلقة بمستضيف الموقع عند الطلب على العنوان {email}.", "Information about the site's host is available on request at {email}.", "Le informazioni sull'hosting del sito sono fornite su semplice richiesta a {email}."],
  "legal.notice.s4.title": ["4. Propriété intellectuelle", "4. الملكية الفكرية", "4. Intellectual property", "4. Proprietà intellettuale"],
  "legal.notice.s4.body": ["L'ensemble des contenus du site (textes, images, logo, charte graphique) est protégé. Toute reproduction sans autorisation écrite préalable est interdite.", "جميع محتويات الموقع (النصوص، الصور، الشعار، الهوية البصرية) محمية. يُمنع أي استنساخ دون إذن كتابي مسبق.", "All site content (text, images, logo, visual identity) is protected. Any reproduction without prior written permission is prohibited.", "Tutti i contenuti del sito (testi, immagini, logo, identità visiva) sono protetti. È vietata qualsiasi riproduzione senza autorizzazione scritta preventiva."],
  "legal.notice.s5.title": ["5. Responsabilité", "5. المسؤولية", "5. Liability", "5. Responsabilità"],
  "legal.notice.s5.body": ["Les informations du site sont fournies à titre indicatif. Le cabinet s'efforce de les tenir à jour mais ne garantit ni l'absence d'erreur ni la disponibilité continue du service.", "المعلومات الواردة في الموقع للاستئناس. يحرص المكتب على تحديثها لكنه لا يضمن خلوّها من الأخطاء ولا استمرارية الخدمة.", "The information on the site is provided for guidance only. The firm strives to keep it up to date but does not guarantee it is error-free or that the service is continuously available.", "Le informazioni del sito sono fornite a titolo indicativo. Lo studio si impegna a mantenerle aggiornate ma non garantisce l'assenza di errori né la disponibilità continua del servizio."],
  "legal.notice.s6.title": ["6. Droit applicable", "6. القانون الواجب التطبيق", "6. Governing law", "6. Legge applicabile"],
  "legal.notice.s6.body": ["Le site est soumis au droit tunisien. Tout litige relève des tribunaux compétents de Tunis.", "يخضع الموقع للقانون التونسي. وتختص بأي نزاع محاكم تونس المختصة.", "The site is governed by Tunisian law. Any dispute falls under the competent courts of Tunis.", "Il sito è soggetto al diritto tunisino. Ogni controversia è di competenza dei tribunali di Tunisi."],

  // SEO
  "seo.terms.title": ["Conditions générales de vente", "الشروط العامة للبيع", "Terms of sale", "Condizioni generali di vendita"],
  "seo.terms.description": ["Conditions de commande, de paiement en deux temps, de livraison et d'annulation des traductions assermentées.", "شروط الطلب والدفع على مرحلتين والتسليم وإلغاء الترجمات المحلّفة.", "Terms for ordering, two-step payment, delivery and cancellation of sworn translations.", "Condizioni di ordine, pagamento in due fasi, consegna e annullamento delle traduzioni giurate."],
  "seo.privacy.title": ["Politique de confidentialité", "سياسة الخصوصية", "Privacy policy", "Informativa sulla privacy"],
  "seo.privacy.description": ["Comment vos données personnelles et vos documents sont protégés.", "كيف تُحمى بياناتكم الشخصية ووثائقكم.", "How your personal data and documents are protected.", "Come vengono protetti i tuoi dati personali e i tuoi documenti."],
  "seo.notice.title": ["Mentions légales", "الإشعارات القانونية", "Legal notice", "Note legali"],
  "seo.notice.description": ["Informations légales sur l'éditeur du site et son activité de traducteur assermenté.", "معلومات قانونية عن ناشر الموقع ونشاطه كمترجم محلّف.", "Legal information about the site publisher and their activity as a sworn translator.", "Informazioni legali sull'editore del sito e sulla sua attività di traduttore giurato."],
};

const LOCALE_INDEX: Record<Locale, number> = { fr: 0, ar: 1, en: 2, it: 3 };

export function getLegalDictionary(locale: Locale): Record<string, string> {
  const index = LOCALE_INDEX[locale];
  return Object.fromEntries(Object.entries(ROWS).map(([key, row]) => [key, row[index]]));
}
